// #F8F8F8;
export const DataSellers = [
  {
    id: 1,
    name: "Meow Cat",
    image: MeowCat,
    price: 1320.0,
    ratings: 0,
    reviews: 0,
    path: `/details/meow-cat`,
  },
  {
    id: 2,
    name: "Mini Meow",
    image: MiniMeow,
    price: 960.0,
    ratings: 0,
    reviews: 0,
    path: "/mini-cat",
  },
  {
    id: 3,
    name: "Ultimate Oreo Cake",
    image: OreoCake,
    price: 1020.0,
    ratings: 0,
    reviews: 0,
    path: "/oreo-cake",
  },
  {
    id: 4,
    name: "M & S",
    image: MSImg,
    price: 2700.0,
    ratings: 0,
    reviews: 0,
    path: "/ms-cake",
  },
  {
    id: 5,
    name: "Oreo Strawberry Topping",
    image: StrawBerry,
    price: 1260.0,
    ratings: 0,
    reviews: 0,
    path: "/strawberry-oreo-topping",
  },
  {
    id: 6,
    name: "Strawberry Topping",
    image: RedStrawBerry,
    price: 2340.0,
    ratings: 0,
    reviews: 0,
    path: "/strawberry-topping",
  },
  {
    id: 7,
    name: "Captain America Theme",
    image: CaptainAmerica,
    price: 2250.0,
    ratings: 0,
    reviews: 0,
    path: "/captain-america-topping",
  },
  {
    id: 8,
    name: "Mini Heart",
    image: MiniHeart,
    price: 840.0,
    ratings: 0,
    reviews: 0,
    path: "/mini-heart",
  },
];
